#############################################################################
# Makefile for building: VisPeptide
# Generated by qmake (2.01a) (Qt 4.8.7) on: ven. janv. 20 15:46:52 2017
# Project:  VisPeptide.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile VisPeptide.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iqt -Isrc/spc -Isrc/ini -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qt/main.cpp \
		qt/mainwindow.cpp \
		src/ini/dictionary.c \
		src/ini/iniparser.c \
		src/spc/main.cpp \
		src/spc/mparser.cpp \
		src/spc/ms1ms2.cpp \
		src/spc/result.cpp \
		src/spc/scoring.cpp \
		src/spc/spectra.cpp \
		src/spc/speptide.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dictionary.o \
		iniparser.o \
		main.o \
		mparser.o \
		ms1ms2.o \
		result.o \
		scoring.o \
		spectra.o \
		speptide.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		VisPeptide.pro
QMAKE_TARGET  = VisPeptide
DESTDIR       = 
TARGET        = VisPeptide

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VisPeptide.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile VisPeptide.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile VisPeptide.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/VisPeptide1.0.0 || $(MKDIR) .tmp/VisPeptide1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VisPeptide1.0.0/ && $(COPY_FILE) --parents qt/mainwindow.h src/ini/dictionary.h src/ini/iniparser.h src/spc/mparser.h src/spc/ms1ms2.h src/spc/result.h src/spc/scoring.h src/spc/spectra.h src/spc/speptide.h .tmp/VisPeptide1.0.0/ && $(COPY_FILE) --parents qt/main.cpp qt/mainwindow.cpp src/ini/dictionary.c src/ini/iniparser.c src/spc/main.cpp src/spc/mparser.cpp src/spc/ms1ms2.cpp src/spc/result.cpp src/spc/scoring.cpp src/spc/spectra.cpp src/spc/speptide.cpp .tmp/VisPeptide1.0.0/ && (cd `dirname .tmp/VisPeptide1.0.0` && $(TAR) VisPeptide1.0.0.tar VisPeptide1.0.0 && $(COMPRESS) VisPeptide1.0.0.tar) && $(MOVE) `dirname .tmp/VisPeptide1.0.0`/VisPeptide1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VisPeptide1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: qt/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qt/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: qt/main.cpp qt/mainwindow.h \
		src/spc/speptide.h \
		src/ini/iniparser.h \
		src/ini/dictionary.h \
		src/spc/spectra.h \
		src/spc/ms1ms2.h \
		src/spc/mparser.h \
		src/spc/result.h \
		src/spc/scoring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o qt/main.cpp

mainwindow.o: qt/mainwindow.cpp qt/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o qt/mainwindow.cpp

dictionary.o: src/ini/dictionary.c src/ini/dictionary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dictionary.o src/ini/dictionary.c

iniparser.o: src/ini/iniparser.c src/ini/iniparser.h \
		src/ini/dictionary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o iniparser.o src/ini/iniparser.c

main.o: src/spc/main.cpp src/spc/speptide.h \
		src/ini/iniparser.h \
		src/ini/dictionary.h \
		src/spc/spectra.h \
		src/spc/ms1ms2.h \
		src/spc/mparser.h \
		src/spc/result.h \
		src/spc/scoring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/spc/main.cpp

mparser.o: src/spc/mparser.cpp src/spc/mparser.h \
		src/spc/ms1ms2.h \
		src/spc/spectra.h \
		src/spc/scoring.h \
		src/spc/result.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mparser.o src/spc/mparser.cpp

ms1ms2.o: src/spc/ms1ms2.cpp src/spc/ms1ms2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ms1ms2.o src/spc/ms1ms2.cpp

result.o: src/spc/result.cpp src/spc/result.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result.o src/spc/result.cpp

scoring.o: src/spc/scoring.cpp src/spc/ms1ms2.h \
		src/spc/spectra.h \
		src/spc/result.h \
		src/spc/scoring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scoring.o src/spc/scoring.cpp

spectra.o: src/spc/spectra.cpp src/spc/ms1ms2.h \
		src/spc/spectra.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectra.o src/spc/spectra.cpp

speptide.o: src/spc/speptide.cpp src/ini/iniparser.h \
		src/ini/dictionary.h \
		src/spc/spectra.h \
		src/spc/ms1ms2.h \
		src/spc/mparser.h \
		src/spc/result.h \
		src/spc/scoring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speptide.o src/spc/speptide.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

