######################################################################
# Automatically generated by qmake (2.01a) lun. févr. 6 10:35:40 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . VisPeptide-src speptide-src/ini speptide-src/spc
INCLUDEPATH += . VisPeptide-src speptide-src/ini speptide-src/spc

# Input
HEADERS += VisPeptide-src/mainwindow.h \
           VisPeptide-src/resultwindow.h 
SOURCES += VisPeptide-src/main.cpp \
           VisPeptide-src/mainwindow.cpp \
           VisPeptide-src/resultwindow.cpp 
