######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 20 15:46:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qt src/ini src/spc
INCLUDEPATH += . qt src/spc src/ini

# Input
HEADERS += qt/mainwindow.h \
           src/ini/dictionary.h \
           src/ini/iniparser.h \
           src/spc/mparser.h \
           src/spc/ms1ms2.h \
           src/spc/result.h \
           src/spc/scoring.h \
           src/spc/spectra.h \
           src/spc/speptide.h
SOURCES += qt/main.cpp \
           qt/mainwindow.cpp \
           src/ini/dictionary.c \
           src/ini/iniparser.c \
           src/spc/mparser.cpp \
           src/spc/ms1ms2.cpp \
           src/spc/result.cpp \
           src/spc/scoring.cpp \
           src/spc/spectra.cpp \
           src/spc/speptide.cpp
