######################################################################
# Automatically generated by qmake (3.0) lun. janv. 23 10:01:07 2017
######################################################################

TEMPLATE = app
TARGET = VisPeptide
INCLUDEPATH += .

# Input
HEADERS += qt/mainwindow.h \
           src/ini/dictionary.h \
           src/ini/iniparser.h \
           src/spc/mparser.h \
           src/spc/ms1ms2.h \
           src/spc/result.h \
           src/spc/scoring.h \
           src/spc/spectra.h \
           src/spc/speptide.h
SOURCES += qt/main.cpp \
           qt/mainwindow.cpp \
           src/ini/dictionary.c \
           src/ini/iniparser.c \
           src/spc/mparser.cpp \
           src/spc/ms1ms2.cpp \
           src/spc/result.cpp \
           src/spc/scoring.cpp \
           src/spc/spectra.cpp \
           src/spc/speptide.cpp
