######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 20 16:57:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
           ../src/spc/speptide.h \
           ../src/ini/iniparser.h \
           ../src/ini/dictionary.h \
           ../src/spc/spectra.h \
           ../src/spc/ms1ms2.h \
           ../src/spc/mparser.h \
           ../src/spc/result.h \
           ../src/spc/scoring.h
SOURCES += main.cpp \
           mainwindow.cpp \
           ../src/spc/speptide.cpp \
           ../src/spc/spectra.cpp \
           ../src/spc/ms1ms2.cpp \
           ../src/spc/mparser.cpp \
           ../src/spc/result.cpp \
           ../src/spc/scoring.cpp
