######################################################################
# Automatically generated by qmake (3.0) lun. janv. 23 10:00:47 2017
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
