######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 31 15:42:32 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h newwindow.h
SOURCES += main.cpp mainwindow.cpp newwindow.cpp
